server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file:///Users/stuholland/Library/CloudStorage/OneDrive-Personal/Documents/Technical/Source/Java/elasticsearch-kafka-microservices/config-server-repository
    #          uri: https://github.com/agelenler/spring-cloud-config-server-repository
    #          default-label: main
    #          username: agelenler
    #          password: ****
    #          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: harry
      password: '73520f41-e6ed-4891-ad7b-d2e76faaaf30'
