server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Crazy-Horse/spring-cloud-config-server-repository
          default-label: main
          username: Crazy-Horse
          password: shSigma86 #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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: harry
      password: 73520f41-e6ed-4891-ad7b-d2e76faaaf30

#configserver:
#  security:
#    enabled: false