spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: harry
      password: 73520f41-e6ed-4891-ad7b-d2e76faaaf30
  security:
    user:
      name: harry
      password: 73520f41-e6ed-4891-ad7b-d2e76faaaf30